---
- name: Intro to Ansible Playbooks
  hosts: all
  gather_facts: True
  become: true
  strategy: free
  tasks:
  - name: Install RedHat epel
    dnf:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'
  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'