---
- name: Intro to Ansible Playbooks
  hosts: all
  gather_facts: True
  become: true
  strategy: free
  vars_files:
    - external_vars.yml
  tasks:
  - name: Copy file 
    ansible.builtin.copy:
      src: ./hello.txt
      dest: ./hello.txt
      mode: '0644'
      owner: "{{ ansible_user }}"
      
  - name: Copy dir 
    ansible.builtin.copy:
      src: ./mydir
      dest: .
      mode: '0644'
      owner: "{{ ansible_user }}"
      
  - name: Install RedHat epel
    dnf:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'
  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
    
  - name: Install RedHat Packages
    dnf:
      name: httpd,iproute-tc,net-tools,pciutils,tcpdump,iftop,iperf3,vim
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'
  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: httpd,iproute-tc,net-tools,pciutils,tcpdump,iftop,iperf3,vim
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
    
    
  - name: Install Ubuntu packages
    apt:
      name: vim,iperf3
      state: present
      force_apt_get: yes
      update_cache: yes
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts ['distribution_major_version'] >= '20'
    
    
  - name: command2
    ansible.builtin.shell: echo {{ mystring }} > {{ myfile }}
    args:
      chdir: .
      creates: "{{ myfile }}"
      
      
  - name: host net tune  
    ansible.builtin.shell: |
        cat >> /etc/sysctl.conf <<EOL
        # allow testing with buffers up to 128MB
        net.core.rmem_max = 536870912 
        net.core.wmem_max = 536870912 
        # increase Linux autotuning TCP buffer limit to 64MB
        net.ipv4.tcp_rmem = 4096 87380 536870912
        net.ipv4.tcp_wmem = 4096 65536 536870912
        # recommended default congestion control is htcp  or bbr
        net.ipv4.tcp_congestion_control=bbr
        # recommended for hosts with jumbo frames enabled
        net.ipv4.tcp_mtu_probing=1
        # recommended to enable 'fair queueing'
        net.core.default_qdisc = fq
        EOL

        sysctl --system

        for dev in `basename -a /sys/class/net/*`; do
            # Turn on jumbo frames
            ip link set dev $dev mtu 9000
        done

        
        exit 0
    args:
      chdir: .
      #creates: "{{ myfile2 }}"
    
   
   
   
